[build]
  publish = "build/"
  command = "sed -i s%API_SERVER%${API_SERVER}%g netlify.toml && npm run build"

[[redirects]]
  from = "/graphql"
  to = "API_SERVER/graphql"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
